added reviews section, styles and js slider
AegisVP/HTML-CSS_54_Group pull request #12
Opened 2022-05-28 14:26 UTC by NazarDonets

2022-05-28 19:58 UTC, AegisVP requested changes

2022-05-28 19:58 UTC, AegisVP commented on src/partials/reviews.html
> +          <div class="swiper-slide">
В першому слайді 'swiper-slide' це `<div>` а `<article>`  має клас 'reviews__slide'.
2-й та 3-й навпаки.

2022-05-28 19:58 UTC, AegisVP commented on src/sass/_reviews.scss
> +$breakpoints: (
breakpoints: 
домовлялись і ментор казав з 320 і до 480 макет responsive (гумовий), після 480 стає адаптивним (завмирає) і змінюється по брейк поінтам.
320 - гумовий mobile - 480 - статичний mobile - 768 - статичний tablet - 1280 - статичний desktop - +

В тебе текст відгуку тягнеться до 768. Все інше добре.

2022-05-29 05:36 UTC, NazarDonets commented on src/partials/reviews.html
> +          <div class="swiper-slide">
Спасибо, поправил 👍

2022-05-29 06:03 UTC, NazarDonets commented on src/sass/_reviews.scss
> +$breakpoints: (
Спасибо, поправил 👍

2022-05-29 07:02 UTC, AegisVP approved these changes

2022-05-29 07:03 UTC, merged