added images
AegisVP/HTML-CSS_54_Group pull request #27
Opened 2022-05-30 09:56 UTC by Rekhlytskyi

2022-05-30 20:20 UTC, AegisVP requested changes

2022-05-30 20:20 UTC, AegisVP commented on src/partials/header.html
> +    <picture>
перенеси картинку після навігації, бо вона перекриває лінки (Contacts взагалі не працює, Review на половину тільки активне в десктоп версії)

2022-05-30 20:20 UTC, AegisVP commented on src/partials/header.html
> +          ./images/pic-donuts_desk.png    1x,
Десктоп версію зображення мабуть треба буде перекачати, якщо екран ширше, обрізані донатси виходять...

2022-05-30 20:20 UTC, AegisVP commented on src/sass/_header.scss
>    font-family: 'Caveat Brush';
є $font--accent замість 'Caveat Brush'...

2022-05-31 08:46 UTC, Rekhlytskyi commented on src/partials/header.html
> +    <picture>
повесил на .navigation__link { position: relative; z-index: 1} 
Перенос картинок в html нужного эффекта не дал.

2022-05-31 08:46 UTC, Rekhlytskyi commented on src/sass/_header.scss
>    font-family: 'Caveat Brush';
готово

2022-05-31 21:18 UTC, AegisVP approved these changes

2022-05-31 21:22 UTC, merged