Fixed/contact
AegisVP/HTML-CSS_54_Group pull request #28
Opened 2022-05-30 12:02 UTC by LebedYulia

2022-05-30 20:52 UTC, AegisVP requested changes

2022-05-30 20:52 UTC, AegisVP commented on src/sass/_container.scss
> -.section {
цей файл не треба видаляти, їм користуються всі.

2022-05-30 20:52 UTC, AegisVP commented on src/sass/util/_variables.scss
> +$color--danger: red;
в коміт краще писати колір в абсолютному форматі (hex або rgb)

2022-05-30 20:52 UTC, AegisVP commented on src/partials/_variables.scss
> +// main style dark beige:         #ab816c, rgb(171, 129, 108)
цей файл в тебе ніде не підключений. мабуть помилково його скопіювала...

2022-05-30 20:52 UTC, AegisVP commented on src/sass/_contact.scss
>  .contact__title {
перевір `font-size` та `font-weight` на різній ширині...

2022-05-30 20:52 UTC, AegisVP commented on src/sass/_contact.scss
> +  transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1);
Анімація не працює бо в тебе ніде не заданий `transform`. Ти задаєш позіцію завдяки `bottom: -12px;`

2022-05-30 20:52 UTC, AegisVP commented on src/sass/_contact.scss
> +  transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1);
Мені якось ріже око коли текст перекриває частину бордера і нема жодних підказок що це навмисно... Спочатку я думав це взагалі баг що воно туди зїхало. Але це суб`єктивно, можемо це обсудити. Реалізовано правильно :)

2022-05-31 06:30 UTC, LebedYulia commented on src/sass/_container.scss
> -.section {
я его удалила потому что он дублируется в папке sass/Util

2022-05-31 06:32 UTC, LebedYulia commented on src/sass/util/_variables.scss
> +$color--danger: red;
+

2022-05-31 06:33 UTC, LebedYulia commented on src/partials/_variables.scss
> +// main style dark beige:         #ab816c, rgb(171, 129, 108)
сорри, удалила

2022-05-31 06:55 UTC, LebedYulia commented on src/sass/_contact.scss
>  .contact__title {
fixed

2022-05-31 23:39 UTC, merged