add SCSS to Program
AegisVP/HTML-CSS_54_Group pull request #29
Opened 2022-05-30 15:35 UTC by u-kolka

Изменил названия картинок своей секции. Добавил стили и адаптив. Кнопку Read more попробовал сделать через JS.

2022-05-30 21:24 UTC, AegisVP requested changes
В тебе всюди де є текст під текстом, марджини схлопуються, а так не має бути. Задай явні марджини щоб тільки один був між елементами.

Ще в мене іконки не вміщаються в свою зону (випадають знизу). Перевір марджини. Мабуть краще позиціонувати наповнення тих секцій по нижньому краю.

Ще в тебе текст не розширюється до 480px бо в тебе стара версія гілки `main`. Зроби `pull` `main`а

2022-05-30 21:24 UTC, AegisVP commented on src/partials/program.html
> +                    <p class="program__text">> A stand up history of donuts</p>
* не треба робити під `<li>` ще й `<p>` якщо більш нічого нема.

2022-05-30 21:24 UTC, AegisVP commented on src/partials/program.html
> +            <h2 class="program__title">Program</h2>
зроби це просто `section__title`

2022-05-30 22:41 UTC, AegisVP requested changes

2022-05-30 22:41 UTC, AegisVP commented on src/sass/_program.scss
> +.features__item:nth-child(1)::before {
путь к изображениям `../images/`

2022-05-30 22:41 UTC, AegisVP commented on src/partials/program.html
> +                            <use href="./src/images/sprite.svg#prog-hat"></use>
путь к изображениям `./images/`

2022-05-31 18:32 UTC, u-kolka commented on src/partials/program.html
> +            <h2 class="program__title">Program</h2>
+

2022-05-31 18:32 UTC, u-kolka commented on src/sass/_program.scss
> +.features__item:nth-child(1)::before {
+

2022-05-31 18:32 UTC, u-kolka commented on src/partials/program.html
> +                            <use href="./src/images/sprite.svg#prog-hat"></use>
+

2022-05-31 23:52 UTC, AegisVP approved these changes
Поки приймаю, трошки підправ марджини знизу та зроби щоб текст з 320px до 480px тягнувся.

2022-05-31 23:54 UTC, AegisVP approved these changes
Поки приймаю, трошки підправ марджини знизу та зроби щоб текст з 320px до 480px тягнувся.

2022-05-31 23:54 UTC, merged