Feature/registration
AegisVP/HTML-CSS_54_Group pull request #30
Opened 2022-05-30 17:10 UTC by bestboost

Привіт! Зорієнтуй чи нормально відображається фон? Друзі ви мої очі у проекті, пишить коменти.
Пончик, та ефекти добавлю в наступному пуші. Дякую)

2022-05-30 23:17 UTC, AegisVP requested changes

2022-05-30 23:17 UTC, AegisVP commented on src/sass/_registration.scss
> +     background-color: $color--main__medium-beige;
не треба задавати колір фону

2022-05-30 23:17 UTC, AegisVP commented on src/sass/_registration.scss
> +            margin-left: 232px;
Ти задаєш марджини по боках 232, але у контейнера вже є падинги 132, тому вони складаються і на десктопі воно не не правильно виглядає (зроби `margin-left: 100px; margin-right: 100px;`).

2022-05-30 23:17 UTC, AegisVP commented on src/sass/_registration.scss
> +.registration-form::before{
Ця лінія є на всіх брейкпоінтах і вона завширшки всього 1px. Якщо ти ій задаєш `border: 1px...` то вона буде шириною мінімум 2px. Зроби `border-right:...` або `border-left:...` (але в твоєму випадку, `border-top:...`)

2022-05-30 23:30 UTC, AegisVP requested changes

2022-05-30 23:30 UTC, AegisVP commented on src/sass/_registration.scss
> +.registration-field__input {
Треба придумати як лейбу поля зберегати, коли щось вводять в поле. Використовувати тільки `placeholder` не гарна ідея. Подивись відео по формам, там є приклад як можна зробити. Ще спишись із @LebedYulia, вона робить блок Contact і там також є поля. Ефект має бути однаковим.

2022-05-31 13:51 UTC, bestboost commented on src/sass/_registration.scss
> +.registration-field__input {
з Юлею погодили, в неї зроблений гарний варіант

2022-06-01 00:30 UTC, AegisVP approved these changes
Коли задаєш марджини, додай ще один класс і там роби додаткові параметри. Якщо ти будеш додавати це в класс .button, всі кнопки на сайті будуть бігати...

2022-06-01 00:30 UTC, AegisVP commented on src/partials/registration.html
> +                    <button type="submit" class="button">Register</button>
Коли задаєш марджини, додай ще один класс і там роби додаткові параметри. Якщо ти будеш додавати це в класс .button, всі кнопки на сайті будуть бігати...

2022-06-01 00:32 UTC, merged