Feature/header
AegisVP/HTML-CSS_54_Group pull request #6
Opened 2022-05-28 09:31 UTC by Rekhlytskyi

Js накатим после мержа хедера и меню в мэйн

2022-05-28 11:10 UTC, AegisVP commented on src/sass/_header.scss
> +        opacity: 0.12;
навіщо це? по макету кнопка повністю видима

2022-05-28 12:44 UTC, AegisVP requested changes
Коменти в файлах

2022-05-28 13:02 UTC, Rekhlytskyi commented on src/sass/_header.scss
> +        opacity: 0.12;
перенес в ховер

2022-05-28 13:03 UTC, Rekhlytskyi commented on src/partials/header.html
> +    <h2 class="header__subtitle">Hosted by Eva Green</h2>
ок, сделаю

2022-05-28 13:03 UTC, Rekhlytskyi commented on src/sass/_header.scss
> +    @extend .link;
размеры иконок указаны в .social__icon. линки только оборачивают их.
пришлю в новом реквесте

2022-05-28 15:14 UTC, Rekhlytskyi commented on src/sass/_header.scss
> +    @media screen and (min-width: 1200px) {
исправил

2022-05-28 20:07 UTC, AegisVP requested changes

2022-05-28 20:07 UTC, AegisVP commented on src/partials/header.html
> +    <h2 class="header__subtitle">Hosted by Eva Green</h2>
`<H1>` залиш, було правильно. `<H2>` має бути `<P>`

2022-05-28 22:01 UTC, AegisVP requested changes

2022-05-28 22:01 UTC, AegisVP commented on src/partials/header.html
> +    <a href="#" class="register__link"> Register</a>
button "Register" links to an anchor named "register-section"
<a href="#register-section" ...

2022-05-29 09:46 UTC, Rekhlytskyi commented on src/partials/header.html
> +    <a href="#" class="register__link"> Register</a>
добавил, но ты же учти, я не вижу пока этой секции :)

2022-05-29 09:51 UTC, AegisVP commented on src/partials/header.html
> +    <a href="#" class="register__link"> Register</a>
да, её пока нету

2022-05-29 12:47 UTC, AegisVP submitted a review, later dismissed

2022-05-29 12:51 UTC, AegisVP approved these changes

2022-05-29 12:52 UTC, merged