features/contact
AegisVP/HTML-CSS_54_Group pull request #7
Opened 2022-05-28 11:51 UTC by LebedYulia

html+scss without validation

2022-05-28 12:41 UTC, AegisVP requested changes

2022-05-28 12:41 UTC, AegisVP commented on src/partials/contact.html
> +                <input class="contact__input" type="email" name="mail" placeholder="Email" required pattern="^([a-z0-9_-]+\.)*[a-z0-9_-]+@[a-z0-9_-]+(\.[a-z0-9_-]+)*\.[a-z]{2,6}$"/>
Це погана ідея використовувати placeholder як підпис для поля. Репета в одному із відео показував як зробити поле із виїжджаючим текстом...

2022-05-28 12:41 UTC, AegisVP commented on src/sass/_contact.scss
> +    @media screen and (max-width: 1279px) {
1279.98px. На деяких броузерах не правильно працює такий запис

2022-05-28 12:41 UTC, AegisVP commented on src/sass/_contact.scss
> +    @media screen and (max-width: 767px) {
теж саме: 767,98px

2022-05-28 12:41 UTC, AegisVP commented on src/sass/_contact.scss
> +    @media screen and (max-width: 767px) {
767.98px

2022-05-28 12:41 UTC, AegisVP commented on src/partials/contact.html
> +                <textarea class="contact__textarea" name="comment" placeholder="Type your question"></textarea>
В мене textarea трохи скролиться вверх-вниз. Краще використовувати <input type="text">

2022-05-28 12:41 UTC, AegisVP commented on src/sass/_container.scss
> +    @media screen and (max-width: 767px) {
max-width: 767.98px

2022-05-28 12:41 UTC, AegisVP commented on src/sass/_container.scss
> +    @media screen and (min-width: 768px) and (max-width: 1279px) {
max-width: 1279.98px

2022-05-28 13:01 UTC, LebedYulia commented on src/sass/_contact.scss
> +    @media screen and (max-width: 1279px) {
Здесь не поняла?

2022-05-28 13:01 UTC, LebedYulia commented on src/sass/_contact.scss
> +    @media screen and (max-width: 767px) {
???

2022-05-28 13:03 UTC, AegisVP commented on src/sass/_contact.scss
> +    @media screen and (max-width: 1279px) {
@media screen and (max-width: 1279.98px)

2022-05-28 13:05 UTC, LebedYulia commented on src/partials/contact.html
> +                <textarea class="contact__textarea" name="comment" placeholder="Type your question"></textarea>
Використовувати що? Не видно что ты написал

2022-05-28 13:06 UTC, AegisVP commented on src/partials/contact.html
> +                <textarea class="contact__textarea" name="comment" placeholder="Type your question"></textarea>
`<input type="text">`

2022-05-28 22:28 UTC, AegisVP commented on src/sass/_contact.scss
> +    @media screen and (max-width: 1279px) {
Там де використовуєтся медіа запрос max-width, на деяких броузерах це працює не правильно, тому треба використовувати число із дробними (1279,9px чи 1279,98px замість 1279px).

2022-05-29 07:15 UTC, AegisVP approved these changes

2022-05-29 07:15 UTC, merged